# Generated by Django 4.1.3 on 2023-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_bikes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='bike',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
