# Generated by Django 4.1.3 on 2023-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_bikes_app', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('CB', 'City Bike'), ('EB', 'E-Bike'), ('MB', 'Mountain Bike'), ('RB', 'Road Bike')], default='CB', max_length=2),
        ),
    ]
