# Generated by Django 4.1.3 on 2023-01-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_bikes_app', '0004_bike_bike_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='location',
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
