# Generated by Django 4.1.3 on 2023-01-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_bikes_app', '0005_remove_review_location_alter_rental_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
    ]
