# Generated by Django 4.1.3 on 2023-01-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_bikes_app', '0006_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_description', models.TextField()),
                ('damage_location', models.CharField(max_length=255)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_bikes_app.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_bikes_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
