# Generated by Django 4.1.3 on 2024-06-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_bikes_app', '0007_damagereport_delete_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
